#!/bin/sh
set -e

## Включаем затребованные расширения PHP.
if [ "${PHP_EXTENSIONS=}" != "" ]; then
	docker-php-ext-enable ${PHP_EXTENSIONS}
fi

## Записываем настройки PHP из переменной окружения.
if [ "${PHP_INI_SETTINGS=}" != "" ]; then
	for option in ${PHP_INI_SETTINGS}; do
		echo "${option}" >> /usr/local/etc/php/conf.d/php.external.ini
	done
fi

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php "$@"
fi

exec "$@"
