#!/bin/bash
##
## Запускает веб-сервер.
##
## См. https://github.com/docker-library/php/blob/master/7.2/stretch/apache/apache2-foreground
##

set -eo pipefail

: "${APACHE_CONFDIR:=/etc/apache2}"
: "${APACHE_ENVVARS:=$APACHE_CONFDIR/envvars}"
if test -f "$APACHE_ENVVARS"; then
	. "$APACHE_ENVVARS"
fi

# Apache gets grumpy about PID files pre-existing
: "${APACHE_RUN_DIR:=/var/run/apache2}"
: "${APACHE_PID_FILE:=$APACHE_RUN_DIR/apache2.pid}"
rm -f "$APACHE_PID_FILE"

# create missing directories
# (especially APACHE_RUN_DIR, APACHE_LOCK_DIR, and APACHE_LOG_DIR)
for e in "${!APACHE_@}"; do
	if [[ "$e" == *_DIR ]] && [[ "${!e}" == /* ]]; then
		# handle "/var/lock" being a symlink to "/run/lock", but "/run/lock" not existing beforehand, so "/var/lock/something" fails to mkdir
		#   mkdir: cannot create directory '/var/lock': File exists
		dir="${!e}"
		while [ "$dir" != "$(dirname "$dir")" ]; do
			dir="$(dirname "$dir")"
			if [ -d "$dir" ]; then
				break
			fi
			absDir="$(readlink -f "$dir" 2>/dev/null || :)"
			if [ -n "$absDir" ]; then
				mkdir -p "$absDir"
			fi
		done

		mkdir -p "${!e}"
	fi
done

# Включаем затребованные модули Apache.
if [ "${APACHE_MODULES=}" != "" ]; then
    a2enmod ${APACHE_MODULES}
fi

# Задаём UID веб-сервера и меняем владельца файлов сайта.
if [ "${FILE_OWNER_UID=}" != "" ]; then
    usermod --uid ${FILE_OWNER_UID} www-data
    chown www-data /var/www
fi

## Включаем затребованные расширения PHP.
if [ "${PHP_EXTENSIONS=}" != "" ]; then
    docker-php-ext-enable ${PHP_EXTENSIONS}
fi

exec apache2 -DFOREGROUND "$@"
